### ISSUE TITLE
'_build_query_href' method AttributeError

### ISSUE THREAD

**Issue by whatabeautifulmemory** [pogzyb/whodap#20]
```python3
import whodap
whodap.lookup_ipv4('128.201.214.5')
```

in rare cases, an 'IPv4Address' object is given instead of the 'str' to '_build_query_href' method.

line 444, in _build_query_href
    href = posixpath.join(rdap_href, 'ip', target.lstrip('/'))
AttributeError: 'IPv4Address' object has no attribute 'lstrip'

**Comment by pogzyb** [comment]
Thank you for finding this bug! I think I solved the issue in #21 . I'm doing some more testing before merging. I will put out a release for version 0.1.7 with this fix today or tomorrow. Thanks again.

**Comment by whatabeautifulmemory** [comment]
thank you! it works perfectly!
