### ISSUE TITLE
[Proposal] Using same same whois keys

### ISSUE THREAD

**Issue by ninoseki** [pogzyb/whodap#30]
I use this library via your `asyncwhois` and I have a use case that uses RDAP and Whois at the same time.

- Query a domain with RDAP
- Fallback to Whois if RDAP does not support the domain (e.g. `example.me`, etc.)

In such case, it's very convenient if `whodap` and `asyncwhois` use the same keys in the parsed output.
But, currently, there are some diffs. For example, 
- `whodap` uses `techniacl_XXX` / `asyncwhois` uses `tech_XXX`
 - `whodap` uses `nameserver` / `asyncwhois` uses `name_servers`

Thus, how about using keys defined in `asyncwhois.parse` to unify the keys?

**Comment by pogzyb** [comment]
Ah yes this is something that I didn't fully fix. Here's a snippet from `asyncwhois.pywhois.py`: 

```
# date keys are mismatched between projects; change these keys to the asyncwhois set.
whois_dict = response.to_whois_dict()
for a_key, b_key in [
    (TLDBaseKeys.EXPIRES, "expires_date"),
    (TLDBaseKeys.UPDATED, "updated_date"),
    (TLDBaseKeys.CREATED, "created_date")
]:
    whois_dict[a_key] = whois_dict.pop(b_key)
# reconcile abuse keys, but don't remove existing key as to not cause issues
# with apps currently depending on them. todo: re-standardize keys in next major release
whois_dict[TLDBaseKeys.REGISTRAR_ABUSE_EMAIL] = whois_dict["abuse_email"]
whois_dict[TLDBaseKeys.REGISTRAR_ABUSE_PHONE] = whois_dict["abuse_phone"]
_self._parser = whois_dict
return _self
```

I was thinking of improving the `asyncwhois` code above rather than modifying this project. Does that sound good?

**Comment by ninoseki** [comment]
Yes it sounds good. Thanks.
